const statesinfo = {
        Warrap:{
        Abyei:{
            Abyei:{
            Abyei_Jong_yom:{},
            Abyeithony:{},
            Gukbial:{},
            Nyinkuac:{}
            },
            Alel:{},
            Ameth_aguok:{
                Todac_II:{},
                Todac_I:{},
                Dungngop:{}
            },
            Mijak:{
                Leu:{},
                Tajalei:{}
            },
            Rumameer:{
                Mabok:{},
                Marial:{}
            }
        },
        Gogrial_East:{
            Nyang:{
                Angernger:{}  
            },
            Pathuon_East:{
                Yiik_adoor:{},
                Mayombiong:{},
                Angernger:{}
            },
            Pathuon_West:{
                Luonyaker:{},
                Majok:{}
            },
            Toch_East:{
                Thuramon:{},
                Nyangdit:{}
            },
            Toch_North:{
                Mayomchol:{},
                Mangolapuk:{}
            },
            Toch_West:{
                Panacier:{},
                Malual_Awien:{}
            }
        },
            Gogrial_West:{
                Riau:{
                    Anguoth:{},
                    Panliet:{},
                    Anguoth:{}
                },
                Kuac_South:{
                    Wunkuelthii:{},
                    Wunkueldit:{},
                    Warkou:{},
                    Doong:{}
                },
                Kuac_North:{
                    Monyjoc:{},
                    Majok:{},
                    Lukluk:{},
                    Kuacjok:{},
                    Anguoi:{}
                },
                Gogrial:{
                    Mandeng:{},
                    Maluilajak:{},
                    Gogrial:{}
                },
                Alek_West:{
                    Alueth:{},
                    Maper:{},
                    Nyokthiang:{}
                },
                Alek_South:{
                    Ngapathian:{},
                    Atukuel:{},
                    Ameeth:{},
                    Alek:{}
                },
                Alek_North:{
                    Mankuaac:{},
                    Malekngok:{},
                    Makuac:{}
                },
                Akon_North:{
                    Mabil:{},
                    Ameth:{}
                },
                Akon_South:{
                    Agaldit:{},
                    Ayien:{},
                    Rup:{}
                }
            },
            Tonj_East:{
                Ananatak:{
                    Ananatak:{},
                    Mideer:{},
                    Ngapanet:{} 
                },
                Makuac:{
                    Wuncuei:{},
                    Payii:{},
                    Makuac:{},
                    Cueialek:{},
                    Ayook:{}
                },
                Malualcum:{
                    Malualcum:{},
                    Kacuat:{},
                    Adol:{}
                },
                Maparah:{
                    Mapara:{},
                    Beknyala:{},
                    Alel:{}
                },
                Mayen:{
                    Wunkuel:{},
                    Mayen:{},
                    Ageer:{}
                },
                Pagor:{
                    Midheer:{},
                    Pagor:{},
                    Puotakou:{}
                },
                Palal:{
                    Akier:{},
                    Aciengreu:{},
                    Mayenramajuong:{},
                    Wunkot:{}
                },
                Paliang:{
                    Rumabuth:{},
                    Anyijong:{},
                    Abior:{}
                },
                Pannhial:{
                    Pannhial:{},
                    Kuenbar:{},
                    Kuelcuk:{}
                },
                Paweng:{
                    Wun_cum:{},
                    Paweng:{},
                    Juolgok:{}
                },
                Wun_liit:{
                    War_lang:{},
                    Palam:{},
                    Pagak:{}
                }
            },
            Tonj_North:{
                Akop:{
                    Acholok:{},
                    Athiengpuol:{},
                    Maguen:{}
                },
                Alabek:{
                    Mading:{},
                    Langkap:{},
                    Adinydou:{}
                },
                Aliek:{
                    Rorkou:{},
                    Patei:{}
                },
                Awuul:{
                    Pagakdit:{},
                    Awuul:{}
                },
                Kirik:{
                    Manyiel:{},
                    Madhiath:{},
                    Achiir:{}
                },
                Manloor:{
                    Pharek_sika:{},
                    Pankot:{}
                },
                Marial_lou:{
                    Adau:{},
                    Puolbar:{}
                },
                Pagol:{
                    Mayenloc:{},
                    Majok:{},
                    Lurchuk:{}
                },
                Rual_bet:{
                    Achol:{},
                    Kuanyiel:{}
                },
                Warrap:{
                    Warrap:{}
                }
            },
            Tonj_South:{
                Jak:{
                    Jak_ameeth:{},
                    Majok:{}
                },
                Manyang_ngok:{
                    Wath_alel:{},
                    Manyiel_thony:{},
                    Cuei_cok:{}
                },
                Thiet:{
                    Yiith_kuel:{},
                    Thiet:{},
                    Ngap_anet:{},
                    Angol:{}
                },
                Tonj:{
                    Wargiir:{},
                    Tonj:{},
                    Malual_muok:{},
                    Aguka:{}
                },
                Wath_alel:{
                    Wanth_Alel_I:{},
                    Pawel:{},
                    Mabior_yar:{},
                    Ayuaath:{}
                }
            },
            
            Twic:{
                Ajak_kuac:{
                    Abyei:{},
                    Marial:{},
                    Molbang:{}
                },
                Akoc:{
                    Tiit:{},
                    Wun_cuei:{},
                    Yiikthon:{}
                },
                Aweeng:{
                    Pagai_Anyuon:{},
                    Maper:{},
                    Majoknoon:{},
                    Bulyom:{}
                },
                Pannyok:{
                    Akak:{},
                    Madiing_luit:{},
                    Majakpagai:{},
                    Tuele:{}
                },
                Turalei:{
                    Nyielabiel:{},
                    Mangok:{},
                    Ayien:{},
                    Anyiel_kuac:{}
                },
                Wunrok:{
                    Tiitcok:{},
                    Kurum:{},
                    Awilgik:{},
                    Ajoong:{}
                }
            }
        },
        Upper_Nile:{
                Ulang:{
                    Ulang:{
                        BulBuong:{},
                        Waaga:{},
                        Ying:{}
                    },
                    Yomding:{
                        RupBuot:{},
                        TorKiel:{}
                    },
                    Kurmuot:{
                        Kuich:{},
                        Toalare:{}
                    },
                    Doma:{
                        Doma:{},
                        Parial:{},
                        Riang:{}
                    }
                    
                },
                Renk:{
                    
                    Jalhak:{
                        Anambul:{},
                        Awarpiny:{},
                        Bajang:{},
                        JalhakCentre:{},
                        Molbok:{}
                    },
                    NorthRenk:{
                        Abukazer:{},
                        EmtidadElJidiet:{},
                        GothRoam:{},
                        HaiTheraya:{},
                        Kidwad:{},
                        Kumshuer:{}
                    },
                    SouthRenk:{
                        Elmasara:{},
                        EmtidadElGidim:{},
                        Joboruna:{},
                        Payuer:{},
                        Suare:{}
                    },
                    Chemmedi:{
                        Bebineeth:{},
                        Buobdit:{},
                        Chemmedi:{},
                        Labior:{}
                    },
                    Geger:{
                        Gerbena:{},
                        Gerger:{},
                        Gospamni:{},
                        Kilo05:{},
                        Kilo15:{},
                        Wunthow:{}
                    }
                },
                Panyikang:{
                    Panyikang:{
                        Bour:{},
                        Diel:{},
                        Door:{},
                        Nyeyar:{},
                        Nyilual:{},
                        Odwoc:{},
                        Pakan:{},
                        Pakwa:{},
                        Patugo:{},
                        Thuor:{},
                        Wilnyang:{},
                        Wuob:{}
                    },
                    Tonga:{
                        Atiego:{},
                        Ayidhag:{},
                        Dhokalal:{},
                        Dienyo:{},
                        Nyibod:{},
                        Nyijuad:{},
                        Papojoc:{},
                        Tonga:{},
                        Yom:{}
                    },
                    Pakang:{
                        Abujop:{},
                        Ajok:{},
                        Obaidhak:{},
                        Pakang  :{}
                    },
                    Panyidwoi:{
                        Obel:{},
                        Pajou:{},
                        Palo:{},
                        Panyidwoi:{},
                        Pathuor :{}
                    },
                    Anakdiar:{
                        EastAnakdiar:{},
                        WesternAnakdiar:{}
                    },
                    Dheteim:{
                        Adot:{},
                        Duh:{},
                        Owachi:{},
                        Thuor:{}
                    }
                },
                Melut:{
                    Panomdit:{
                        Belgo:{},
                        Malek:{},
                        Panhomdit:{},
                        Panomthii :{}
                    },
                    Wunamum:{
                        Agordiit:{},
                        Leweng:{}
                    },
                    Melut:{
                        Tieb:{},
                        Torkuach:{}
                    },
                    Paloch:{
                        Baping:{},
                        NewPaloch:{},
                        Padiet:{},
                        Paloch:{}
                    },
                    Bimachuk:{
                        Aboron:{},
                        Pabony:{},
                        Parag:{},
                        Thaak:{},
                        Torthiang:{}
                    },
                    Galdora:{
                        Chuai:{},
                        Galdora:{},
                        ThiengRial:{}
                    }
                },
                Manyo:{
                    
                    Wedakona:{
                        Aderi:{}
                    },
                    Kaka:{
                        Akorwa:{},
                        Kaka:{},
                        Thorguang:{},
                        Uriang:{}
                    },
                    Magenist:{
                        Kidguang:{},
                        Ommir:{}
                    },
                    Wedakona:{
                        Ashik:{},
                        Ayat:{},
                        Bushara:{},
                        Ganwad:{},
                        Garang:{},
                        Kuek:{},
                        Kuria:{},
                        Mamor:{},
                        NewSite:{},
                        Okun:{},
                        Ommar:{}
                    },
                    Adhidwoi:{
                        Athidwoi:{}
                    }
                },
                Malakal:{
                    Ogot:{
                        Ogot:{},
                        Padit:{},
                        Wau:{}
                    },
                    SouthernMalakal:{
                        Assosa:{},
                        Bam:{},
                        Dengerishufi:{},
                        Goni:{},
                        Tarawa:{}
                    },
                    Lelo:{
                        Makal:{},
                        Obwa:{},
                        Werjuok:{}
                    },
                    NorthernMalakal:{
                        Elbesery:{},
                        HaiChathi:{},
                        HaiDinka:{},
                        HaiMathar:{},
                        HaiNuba:{},
                        HaiShuluk:{},
                        HaiZandi:{},
                        Luakat:{},
                        SoraMulkie:{}
                    },
                    CentralMalakal:{
                        Jalaba:{},
                        Mederia:{},
                        RayElMesiri:{}
                    },
                    EasternMalakal:{
                        Biathin:{},
                        Emtidad:{},
                        HaiSah:{},
                        HaiTelevision:{},
                        Sorajalaba:{}
                    }
                },
                Maiwut:{
                    Olang:{
                        Oleng:{},
                        Plang:{},
                        Tang:{},
                        Zink:{}
                    },
                    Pagak:{
                        Yuayding:{}
                    },
                    Kigila:{
                        Abajabe:{},
                        Wadesa:{}
                    },
                    Maiwut:{
                        Kulang:{},
                        Mataar:{},
                        Palang:{},
                        Parich:{}
                    },
                    Jekow:{
                        Oriang:{},
                        Turow:{},
                        ZarZaar:{}
                    },
                    Jotoma:{
                        Kumchuk:{},
                        Nyangore:{},
                        Pingpil:{},
                        Woor:{},
                        Wunkir:{},
                        WunNgony:{}
                    }
                },
                Maban:{
                    Jinmakda:{
                        Banjiella:{},
                        Jamam:{},
                        Kidwa:{},
                        Kuatta:{}
                    },
                    KhorElAmer:{
                        Dhuma:{},
                        Dielaji:{},
                        Sheren:{},
                        Yiellen:{}
                    },
                    Boung:{
                        Boung:{},
                        Chetta:{},
                        Thuoji:{}
                    },
                    Jinkuata:{
                        Bansholi:{},
                        Bunyken:{},
                        Kongo:{},
                        Kuunyjuria:{},
                        Piekeji:{}
                    },
                    Banashowa:{
                        Banashowa:{},
                        Dangeji:{},
                        Doungoji:{},
                        Kanyaji:{},
                        Kenngoyo:{},
                        Kewoji:{},
                        Leka:{},
                        Liang:{},
                        Yahogi:{},
                        Yienaji:{}
                    }
                },
                LuakpinyNasir:{
                    Nasir:{
                        Dhuording:{},
                        Guanya:{},
                        Majak:{},
                        Nasir:{},
                        Torjuoc:{}
                    },
                    Roam:{
                        Dong:{},
                        Gechreng:{},
                        GuirNguntong:{},
                        Luakwien:{},
                        Roam:{},
                        WechKuach:{}
                    },
                    Mading:{
                        Boreel:{},
                        Boul:{},
                        Chotkuach:{},
                        Dukmar:{},
                        Koatwetha:{},
                        Nyarenge:{},
                        Tin:{}
                    },
                    Maker:{
                        GurNyang:{},
                        Maker:{},
                        Tip:{}
                    },
                    KiechKuon:{
                        DhekDheek:{},
                        KiechKuon:{},
                        KiechTwo:{},
                        Koat:{},
                        Lonylok:{}
                    },
                    KuerengeKe:{
                        Mandeng:{},
                        Nor:{},
                        Torkech:{}
                    },
                    Dingkar:{
                        Dhalap:{},
                        Dingkar:{},
                        Lualeyaak:{},
                        Nayaar:{}
                    },
                    Jikmir:{
                        Jikmir:{},
                        Kier:{},
                        Nyetot:{}
                    }
                },
                Longochuk:{
                    Pamach:{
                        Belwang:{},
                        Mabor:{},
                        Palguop:{},
                        Pamach:{},
                        Tichak:{},
                        Tochwengthok:{},
                        WechNhial  :{}
                    },
                    Wudier:{
                        Kiergaw:{},
                        Longechuk_II:{}
                    },
                    Longochuk:{
                        Banyjiel:{},
                        Jangok:{},
                        Werweng:{},
                        Wunthow:{}
                    },
                    Malual:{
                        Malou:{}
                    },
                    Dajo:{
                        Dajo:{},
                        PaiTahth:{}
                    },
                    Guelguk:{
                        Chotgiel:{},
                        Mangok:{}     
                    }
                },
                Fashoda:{
                    KodokTown:{
                        Debor:{},
                        KodokTown:{},
                        Leem:{}
                    },
                    Lul:{
                        Buol:{},
                        Fashoda:{},
                        Wichreak:{}
                    },
                    Dethok:{
                        Abienyay:{},
                        Achak:{},
                        Alel:{},
                        Dithok:{},
                        Kunychang:{},
                        Pabiw:{}
                    },
                    Kodok:{
                        Gollo:{},
                        Gulbany:{},
                        Kodok:{},
                        Nyigir:{}
                    }
                },
                Baliet:{
                    Rom:{
                        BaiAdor:{},
                        BaiAdor:{},
                        BaiAdor:{},
                        BaiAdor:{},
                        BaiAdor:{},
                        BaiAdor:{}
                    },
                    Wunthow:{
                        BaiAdor:{},
                        Majak:{},
                        Wunthow :{}
                    },
                    Nyongkuach:{
                        Duut:{},
                        Pagak:{},
                        Wekjur:{}
                    },
                    Nyongrial:{
                        BaiAdor:{},
                        BaiAdor:{},
                        BaiAdor:{}
                    },
                    GelAchiel:{
                        Wunthow:{}
                    },
                    Kuel:{
                        Miareng:{}
                    },
                    Akoka:{
                        Wunthow:{}
                    },
                    Akotweng:{
                        Akotweng:{},
                        Loyier:{},
                        Pelderoroway:{}
                    },
                    Abwong:{
                        Abwong:{},
                        Rualtom:{},
                        Wunbut:{}
                    },
                    Adong:{
                        Abei:{},
                        Awier:{},
                        Dakjur:{}
                    }
                },

        },
        Jonglei:{
            Uror:{
                Karam:{
                    Dhuony:{},
                    Duok:{},
                    Duol:{},
                    Karam:{},
                    Kiirgai:{},
                    Ngueny:{},
                    Patuak:{},
                    Pulngere:{},
                    Yiethdeng:{}
                },
                Motot:{
                    Chueidok:{},
                    Dakriang:{},
                    Gokgoak:{},
                    Guic:{},
                    Kapkong:{},
                    Motot :{}
                },
                Pathai:{
                    Kuerdiek:{},
                    Kuerguarnyabiel:{},
                    Paluony:{},
                    Panom:{},
                    Pathai:{},
                    Pulchuor:{},
                    Riangchengoi:{},
                    Riangchukuel :{}
                },
                Payai:{
                    Dhuony:{},
                    Kuel:{},
                    Kuombuong:{},
                    Paritet:{},
                    Payai:{},
                    Thardiok:{},
                    Thempiny:{},
                    Uror :{}   
                },
                Pieri:{
                    Gaatweel:{},
                    Guenchat:{},
                    JokrialA:{},
                    Jundit:{},
                    Kueldhal :{}
                },
                Puolchuol:{
                    JokrialB:{},
                    Nyakor:{},
                    Rubliah:{},
                    Tangnyang:{},
                    Weikey :{}
                },
                Tiam:{
                    Jokduel:{},
                    Panyang:{},
                    Pathat:{},
                    Yian :{}
                },
                Wuror:{
                    Kuerluot:{},
                    Panyuok:{},
                    Uleng:{},
                    Week:{}
                }
            },
            TwicEast:{
                Ajuong:{
                    Akuoch:{},
                    Ngawai:{},
                    Paliau:{},
                    Paweel:{},
                    Wutlier :{}
                },
                Kongor:{
                    Garalei:{},
                    Pageer:{},
                    Pawel:{},
                    Payom:{}
                },
                Lith:{
                    Ayathgak:{},
                    Kiir:{},
                    Mabior:{},
                    Malei:{},
                    Pabarcikok:{},
                    Wunthou:{}
                },
                Nyuak:{
                    Baping:{},
                    Lualajokbil:{},
                    Matjak:{},
                    Pator:{},
                    Pongborong:{},
                    Wangulei:{},
                    Wutkoro:{}
                },
                Pakeer :{
                    Adubaar:{},
                    Maar:{},
                    Marial:{},
                    Nyany:{},
                    Piol:{}
                }  
            },
            Pochalla:{
                Adongo:{
                    Ajwara:{},
                    Alari:{},
                    Alieo:{},
                    Kutnguech:{},
                    Ojwa:{},
                    Otugu:{},
                    Pithduong:{}
                },
                Akiela:{
                    Odiek:{},
                    Okadi:{},
                    Ongeda:{},
                    Pinythin :{}
                },
                Burator:{
                    Daktek:{},
                    Juthanguata:{},
                    Nyuom :{}
                },
                Omiela:{
                    Ogin:{},
                    Ojalo:{},
                    Omiela:{}
                },
                Pochalla:{
                    Achari:{},
                    Ajiango:{},
                    Lokri:{},
                    Longo:{},
                    Obudi:{},
                    Odongol:{},
                    Ogaa:{},
                    Ojangbae:{}
                }

            },
            Pibor:{
                Boma:{
                    Bayen:{},
                    Churi:{},
                    Itti:{},
                    Jonglei:{},
                    Kaiwa:{},
                    Nyalongoro:{},
                    Nyat:{},
                    Orgin:{}  
                },
                Gumuruk:{
                    Erit:{},
                    GumurukCentre:{},
                    Kelero:{},
                    Kotile:{},
                    Lawol:{},
                    Manyloden:{},
                    Manymar:{},
                    Ngachavarachiz:{},
                    Tangnyang:{},
                    Viveno:{},
                    Yot:{}
                },
                Kiziongora:{
                    Angaimo:{},
                    Koradef:{},
                    Kuruono:{},
                    Nawukali:{},
                    Ziriai:{}
                },
                Lekuangole:{
                    Chindor:{},
                    Dhalmany:{},
                    Kongor:{},
                    Lekuangole:{},
                    Manydhing:{},
                    Manytakar:{},
                    Monychak:{},
                    Nyergeny:{},
                    Tontol:{},
                    Wunngony:{}
                },
                Marow:{
                    Ashwa:{},
                    Berege:{},
                    Lokopilmoro:{},
                    Morech:{},
                    Munyma:{},
                    Ngachazoch:{},
                    Rabarab:{},
                    Turen:{}
                },
                Miwono:{
                    Mewun:{},
                    Rumit :{}
                },
                Pibor:{
                    Beh:{},
                    Kavachoch:{},
                    Kuluzur:{},
                    Kuyi:{},
                    Lenyirieth:{},
                    Manyirany:{},
                    Manyumen:{},
                    Nyamachul:{},
                    Pibor:{},
                    Thangong:{},
                    Wunkok :{} 
                },
                Verteth:{
                    Kelebeta:{},
                    Manybicha:{},
                    Murlil:{},
                    Murteden:{},
                    Ngoli:{},
                    Nuer:{},
                    Tolwa:{}
                }
            },
            Old_Fangak:{
                Mareang:{
                    Mareang:{},
                    Nyadin:{},
                    Toch:{}
                },
                OldFangak :{
                    Chotbara:{},
                    OldFangak:{},
                    Pulpam :{}
                },
                Paguer:{
                    Keew:{},
                    Kuerpon:{},
                    Thokchak :{}
                },
                Phom:{
                    Haibichuolkon:{},
                    HaiMalakia:{},
                    Haimunezemaat:{},
                    HaiMuwezefin:{},
                    HaiTijar:{},
                    HaiVetenary :{}    
                }

            },
            Nyirol:{
                Chuil:{
                    Chuil:{},
                    Dieni:{},
                    Kurmayom:{},
                    Pathiel:{},
                    Wunegeet:{},
                    Yakkuach:{}
                },
                Nyambor:{
                    Limkuon:{},
                    Ngueng:{},
                    Nyambor:{},
                    Riang:{},
                    Rupchak:{}
                },
                Pading:{
                    Boiloch:{},
                    Pakum:{},
                    Weidieu:{},
                    Weithep:{},
                    Wenyal:{},
                    Yardit:{}
                },
                Pulturuk:{
                    Banyjur:{},
                    Barriak:{},
                    Kot:{},
                    Kuei:{},
                    Panyang:{},
                    Panyangluel:{}
                },
                Thol:{
                    Dualjany:{},
                    Lankien:{},
                    Liawut:{},
                    Nyatim:{},
                    Pagor:{},
                    Puokbor:{},
                    Thol:{},
                    Tut:{}
                },
                Waat :{
                    Boduot:{},
                    Bourdit:{},
                    Kuemlet:{},
                    Rim:{},
                    Wechdeng:{},
                    Wunbil:{}
                }
            },
            Duk:{
                Ageer:{
                    Patuatnoi:{},
                    Pawai:{},
                    Poktap :{}
                },
                Dongchak:{
                    Amiel:{},
                    Chiraanmaar:{},
                    Kabek:{},
                    Kawer:{},
                    Pakam:{},
                    Wunthor:{}  
                },
                Padiet:{
                    Ayueldit:{},
                    Bongjok:{},
                    Dorok:{},
                    Padiet:{}
                },
                Pagak:{
                    Dhuony:{},
                    Pagak:{},
                    Tindiir:{}
                },
                Panyang:{
                    Baan:{},
                    Derkuach:{},
                    Kactong:{},
                    Pagaleng:{},
                    Pajut:{},
                    Turu :{}
                },
                Payuel :{
                    Jolong:{},
                    Mareng:{},
                    Payuel:{}
                }
            },
            Peji:{
                Alam:{
                    Alam:{},
                    Ngong:{}
                },
                Atar:{
                    AtarSchool:{},
                    ChueiArdebThaar:{},
                    Dengluat:{},
                    Pachot:{},
                    WunKiir :{}   
                },
                Belewach:{
                    Belwech:{}
                },
                Kaldak:{
                    Kaldak:{},
                    Piji:{}
                },
                Korwach:{
                    Amatnyang:{},
                    Chuei:{},
                    Korwai:{},
                    TuomTim:{}
                },
                Mareng:{
                    Gokjack:{},
                    Manbay:{}
                },
                Nyainthokmalual:{
                    MalualBay:{}
                },
                Wunlem:{
                    WunLem:{}
                }
            },
            Bor_South:{
                Anyidi:{
                    Chueimagon:{},
                    Mareng:{},
                    Thianwei:{}
                },
                Baidit:{
                    Akayiech:{},
                    Makolchuei:{},
                    Manydeng:{},
                    Mathiang:{},
                    Mayen:{},
                    Ngatinag:{},
                    Tong:{}
                },
                Bor:{
                    Arek:{},
                    Bortown:{},
                    Gaakyuom:{},
                    Jarwong:{},
                    Langbar:{},
                    Pakua:{},
                    Panapet:{},
                    Tuonygeau:{}
                },
                Jalle:{
                    Akuaideng:{},
                    Jalle:{},
                    Kolmarek:{},
                    Kueijuet:{}
                },
                Kolnyang:{
                    Chueikeer:{},
                    Gak:{},
                    Kolnyang:{},
                    Pariak:{}
                },
                Makuach:{
                    Kapat:{},
                    Konbek:{},
                    Makuach:{},
                    Werkok:{}
                }
            },
            Ayod:{
                Ayod:{
                    Bool:{},
                    Kalibalek:{},
                    Kuei:{},
                    Reng:{} 
                },
                Kuachdeng :{
                    Biei:{},
                    Buk:{},
                    Panah:{},
                    Rakyen:{}
                },
                Kurwai:{
                    Haat:{},
                    Matime:{},
                    Nyoat:{},
                    Pakuem:{},
                    Riang:{},
                    Wau2:{}
                },
                Mogok:{
                    Gaar:{},
                    Kandak:{},
                    Panyang:{},
                    Thuop :{}
                },
                Pagil:{
                    Cuilbong:{},
                    Pagil:{},
                    WechDeng:{},
                    WechDieng:{}
                },
                Pajiek:{
                    Chuek:{},
                    Keer:{},
                    Nyawit:{},
                    Pajiek:{},
                    Yian:{}
                },
                Wau:{
                    Biey:{},
                    Jiech:{},
                    Torkei:{},
                    WanMachar:{},
                    Wau:{}
                }
            },
            Akobo:{
                Alali:{
                    Alali:{},
                    Aparawanga:{},
                    Ojoky:{}   
                },
                Barmach:{
                    Dangjop:{},
                    Manjung:{},
                    Ulang:{},
                    Wechjal:{}
                },
                Bilkey:{
                    Okau:{},
                    OldAkobo:{},
                    Rine:{},
                    Weijiokni:{}
                },
                Buong:{
                    Balok:{},
                    BuongKuel:{},
                    Manguet:{},
                    Matar:{}
                },
                Dengjok:{
                    Gakdong:{},
                    Kier:{},
                    Nukta:{},
                    Wecpuot:{}
                },
                Diror:{
                    Dik:{},
                    Kaikueny:{},
                    Padoi:{},
                    Tangnyang :{}
                },
                Nyandit:{
                    Chiban:{},
                    Mer:{},
                    Obor:{},
                    Padida:{}
                },
                Walgak:{
                    Kuernyuon:{},
                    Walgak:{},
                    Wechyakuach:{},
                    Wunkuel:{}
                }
            }

        },
        Unity:{
            Rubkotne:{
                BentiuTown:{
                    Bilnyang:{},
                    Bimruok:{},
                    Derra:{},
                    HaiIngass:{},
                    Kalebalek:{},
                    Kordapdap:{},
                    Nyuenypiu:{}
                },
                Budaang :{
                    Chotchara:{},
                    Mathiang:{},
                    Riaideng:{},
                    Rotriak:{}
                },
                Dhorbor:{
                    Mathoyoh:{},
                    Ngapngoap:{}
                },
                Kaljak:{
                    Bielchier:{},
                    Diem:{},
                    Kaljaak:{},
                    TochRur:{}
                },
                Ngop:{
                    Koat :{} 
                },
                Nhialdiu:{
                    Chanlual:{},
                    Chuor:{},
                    Manwalbar:{},
                    Ngopthoan:{},
                    Nhialdiu:{},
                    Nyaromne:{},
                    Thiet:{},
                    Tochluak:{},
                    Tongedol:{},
                    Waak:{}
                },
                Panhiany:{
                    Dhorbor:{},
                    Panhiany:{},
                    Riaw :{}  
                },
                Rubkotne:{
                    Bany:{},
                    Barmalual:{},
                    Kuerthoah:{},
                    Luor:{},
                    Ngaplel:{},
                    Nying:{},
                    Pakur:{},
                    Tong:{},
                    Yoanyang:{}
                },
                Wathjaak:{
                    Rubnyagai:{}
                }
            },
            Pariang:{
                Aliiny:{
                    Alilang:{},
                    Athony:{},
                    Kaigo:{},
                    Marapien:{},
                    Rukchuk:{},
                    Wunkur:{}
                },
                Biu:{
                    Akot:{},
                    Aliap:{},
                    Aloch:{},
                    Bhal:{},
                    Burdeng:{},
                    Lele:{},
                    Miac :{}
                },
                Jamjang:{
                    Akok:{},
                    Alual:{},
                    Aruch:{},
                    Awuch:{},
                    Gomlel:{},
                    Jamjang:{},
                    Mankuok:{},
                    Panpeth :{}
                },
                Nyeel:{
                    Akotweng:{},
                    Kong:{},
                    Kumagon:{},
                    Nyeel:{},
                    Yar :{}
                },
                Pariang:{
                    Guengalauth:{},
                    Waukok:{},
                    Wunlit:{}
                },
                Werthen:{
                    Jaw:{},
                    Nyarweng:{},
                    Panthur:{},
                    Panyang:{},
                    Wungok:{},
                    Yida:{}
                },
                Wunkur:{
                    Arech:{}
                }
            },
            Panyijiar:{
                Ganyliel:{
                    Dekom:{},
                    Ganyliel:{},
                    Panhial:{},
                    Patuor:{} 
                },
                Kol:{
                    Jiliew:{},
                    Kol:{},
                    Machar:{},
                    Pathiel:{}
                },
                Mayom:{
                    Barjangni:{},
                    Kanynhial:{},
                    Maluak:{},
                    Mayom  :{}
                },
                Nyal:{
                    Nyadong:{},
                    Nyal:{},
                    Palual:{},
                    Yup  :{}
                },
                Pachaar:{
                    Makur:{},
                    Pachaar:{},
                    Pariel:{},
                    Parun :{}
                },
                Pachak:{
                    Maper:{},
                    Moorgok:{},
                    Nyajang:{},
                    Pachak  :{}
                },
                Pachienjok:{
                    Dhornyangni:{},
                    Pachienjok:{},
                    Pakham:{}
                },
                Panyijiar:{
                    Bonglach:{},
                    Chuk:{},
                    Panyijiar:{},
                    Pothlor:{}
                },
                Thoarnhoum:{
                    Jiech:{},
                    Kei:{},
                    Mathiang:{},
                    Thoarnhoum:{}
                },
                Tiap:{
                    Liedit:{},
                    Pabuong:{},
                    Taweng:{},
                    Tiap:{}
                }


            },
            Mayom:{
                Bieh:{
                    Bieh:{},
                    Norgai:{},
                    TongTuol:{},
                    Tuochloka:{}
                },
                Kuerbuone:{
                    Kuerbuona:{},
                    Mayom:{},
                    Nyigar:{},
                    Paluang:{},
                    TuocNgiine:{}, 
                },
                Kueryiek:{
                    Kueryana:{},
                    Kueryiek:{},
                    Northony:{},
                    Rialthiang :{}
                },
                Mankien:{
                    Kernyang:{},
                    Mankien:{},
                    Puor :{}
                },
                Ngop:{
                    Juom:{},
                    Mangar:{},
                    Namyour  :{}
                },
                Pup:{
                    Mathiang:{},
                    Normanlok:{},
                    Nyakuole:{},
                    Panhial :{}
                },
                Riak:{
                    Chotchara:{},
                    Kualkuony:{},
                    Lienggiere:{},
                    Ngoany:{},
                    Riak :{}
                },
                Ruathnyibuol :{
                    Koackoac:{},
                    Norjuoy:{},
                    Nyoat:{},
                    Ruadhnyibol :{}
                },
                WangbuorI:{
                    Madul :{} 
                },
                WangbuorII:{
                    Turkey:{}
                },
                WangbuorIII:{
                    Borbor:{},
                    Wangbuor:{},
                    Wurach:{}
                },
                Wangkei :{
                    Loathjuat:{},
                    Thargene:{},
                    Wangkei:{},
                    Wathoak:{},
                    Wichok:{}
                }
            },
            Mayendit:{
                Bor:{
                    Dorbuona:{},
                    Puulual:{}
                },
                Dablual:{
                    Daplual:{},
                    Dhorleak:{},
                    Kah:{},
                    Reri:{}
                },
                Luom:{
                    Leah:{},
                    Luom:{}
                },
                Maal:{
                    Dhortheir:{},
                    Maal  :{}
                },
                Pabuong:{
                    Bathjob 
                },
                Rubkuay:{
                    Buoth:{},
                    Dhornyiet:{},
                    Rubkuay:{},
                    Rubnor :{} 
                },
                Thaker:{
                    Gamriek:{},
                    Kuok:{},
                    Maper:{},
                    Thaker :{}  
                },
                Tharjiath :{
                    Lang:{},
                    Malbeak:{},
                    Tharjiath:{}
                },
                Tutnyang:{
                    Dhoryiel:{},
                    Tutnyang:{}
                }
            },
            Leer:{
                Adok:{
                    Kumagaab:{},
                    Norkong:{},
                    Pakuem :{}
                },
                Bou:{
                    Bou:{},
                    Koam:{},
                    Kur:{},
                    Pawiny:{}
                },
                Dok:{
                    Dok:{},
                    Nyadiar:{},
                    Payak:{},
                    Rubchiar :{}    
                },
                Guat:{
                    Guat:{},
                    Pading:{},
                    Tuak  :{}
                },
                JuongKang:{
                    Dhar:{},
                    Kulier:{},
                    Nyony  :{}
                },
                Padeah:{
                    Padeah:{},
                    Tharuop :{}
                },
                Pilieny:{
                    Kaigai:{},
                    Panhiam:{},
                    Pilieny :{}
                },
                Yang :{
                    Thonyor:{},
                    Waanyni:{}
                }
            },
            Koch:{
                Boaw:{
                    Boaw:{},
                    Gor:{},
                    Loang:{},
                    Mar:{},
                    Pham:{}
                },
                Gany:{
                    Dengdet:{},
                    Gany:{},
                    Guar:{},
                    Kuit:{},
                    Leah:{}
                },
                Jaak:{
                    Bool:{},
                    Dijuil:{},
                    Guol:{},
                    Jaak:{},
                    Rier:{},
                    Tharnor:{},
                    Tongadol:{}
                },
                Kuachlual:{
                    Baang:{},
                    Bargok:{},
                    Golpiny:{},
                    Padeah:{}
                },
                Ngony:{
                    Biehkuol:{},
                    Dharbor:{},
                    Garyian:{},
                    Kulier:{},
                    Mirmir:{},
                    Nyony:{},
                    Patit:{}
                },
                Norbor:{
                    Gaap:{},
                    Ganglet:{},
                    Jaak:{},
                    Norbor:{}
                },
                Pakur:{
                    Buoth:{},
                    Nyalou:{},
                    Pakur:{},
                    Tharyier:{},
                    Wumlit:{}
                }
            },
            Guit:{
                Guit:{
                    Chotyiel:{},
                    HaiKir:{},
                    HaiTiak:{},
                    Salaam:{}
                },
                Kedad:{
                    Lathtang:{},
                    Muomkuan:{},
                    Wicruop:{}
                },
                kuach:{
                    Kad:{},
                    Kuach:{},
                    Kuerkuol:{},
                    Nying:{},
                    Thuom:{}
                },
                Kuerguini:{
                    Dhorbor:{},
                    Kuerguini:{},
                    Pamkuy:{},
                    Thoan:{}
                },
                Niemni:{
                    Bil:{},
                    Kuanyrow:{},
                    Kuergeng:{},
                    Padhuony:{},
                    Zorreak:{}
                },
                Nyathoar:{
                    BurBur:{},
                    Dengbow:{},
                    Keach:{},
                    Thepchak:{}
                },
                Wathnyona:{
                    Kuerbouna:{},
                    Thorgow:{},
                    Wathnyona:{}
                }

            },
            Abiemnhom:{
                Abiemnhom:{
                    Pangok:{},
                    Pathiew:{},
                    Wungok:{}
                },
                Aworpiny:{
                    Aworpiny:{}
                },
                Manjoga:{
                    Lorpiny:{}
                },
                Panyang:{
                    Awila:{}
                }
            }
        },
        Western_Bahr_el_Ghazal:{
            Wau:{
                Wau_South:{
                    Agok:{},
                    BaziaJedid:{},
                    HaiKrashA:{},
                    HaiKrashB:{},
                    Jalaba:{},
                    JebelA:{},
                    JebelB:{},
                    JebelKheir:{},
                    Jezira:{},
                    Kosti:{},
                    Masna:{},
                    Mutamadia:{},
                    Muwzifin:{},
                    Nazareth:{},
                    NewSite:{}
                },
                Wau_North:{
                    AweilJedid:{},
                    DarajatEast:{},
                    DarajatWest:{},
                    HaiBafara:{},
                    HaiDinka:{},
                    HaiFahalZande:{},
                    HaiFallata:{},
                    HaiJadid:{},
                    HaiKalvario:{},
                    HaiKhorgana:{},
                    HaiSikaHadid:{},
                    Ismailiya:{},
                    Lokloko :{} 
                },
                Kpaile:{
                    Gittan:{},
                    Kpaile:{},
                    Rafili:{},
                    Taban:{} 
                },
                Besselia:{
                    Abushaka:{},
                    Besselia:{},
                    Kaabi:{},
                    KhorGana:{},
                    Mboro:{},
                    Ngolimbo:{}   
                },
                Bagari:{
                    Bagari:{},
                    Bringi:{},
                    Bussere:{},
                    Momoi:{},
                    Ngisa:{},
                    Ngodakala:{}
                }

            },
            Raga:{
                Uyujuku:{
                    Kuru:{},
                    Sopo:{},
                    Uyujuku:{},
                    Yabulu :{}  
                },
                Ringi:{
                    BoroMedina:{},
                    DiemJallab:{},
                    Katta:{},
                    Menamba:{}
                },
                Raga:{
                    Gossinga:{},
                    Mbambara:{},
                    RagaNorth:{},
                    RagaSouthA:{},
                    RagaSouthB:{}
                },
                Kafakengi:{
                    KafiaKengi:{}
                },
                Ere:{
                    Balballa:{},
                    BoroBahr:{},
                    Magwa:{},
                    Timsah:{}
                }
            },
            Jur_River:{
                Wau_Bai:{
                    MabiorAbiem:{},
                    Makuac:{},
                    Nyinakok:{},
                    Tharkueng:{} 
                },
                Udici:{
                    Atido:{},
                    Gette:{},
                    Kayango:{},
                    Udici:{}
                },
                Rocrocdong:{
                    Achot:{},
                    Rocrocdong:{},
                    Wathalelo:{}
                },
                Marial_Bai:{
                    Achongchong:{},
                    AlelChok:{},
                    Kuom:{},
                    MarialBai:{},
                    Rakbak   :{}
                },
                Kuajiena:{
                    Alur:{},
                    DangAcak:{},
                    Kuajiena:{},
                    Mbili:{}
                },
                Kangi:{
                    Alelthony:{},
                    Athor:{},
                    Gumel:{},
                    Kangi:{},
                    Tikou:{}
                }
            }

        },
        Northern_Bahr_el_Ghazal:{
            Aweil_West:{
                Mariem_East:{
                    Ajuet_Alel:{},
                    Ajuet_Toich:{},
                    Aweil_Alel:{}

                },
                Mariem_West:{
                    Chimel_Dit:{},
                    Chimel_Makem:{},
                    Chimel_Thii:{}
                },
                Gomjuer_East:{
                    Aguat:{}, 
                    War_Kou:{},
                    Wet_wil:{}
                },
                Gomjuer_West:{
                    Amudho:{},
                    Marolbuol:{}
                },
                Gomjuer_Centre:{
                    Gomjuer_Thii:{}
                },
                Ayat_West:{
                    Akuang_rial:{},
                    Malek_Mayar:{},
                    Nyin_Buoli:{}
                },
                Ayat_East:{
                    Majok_Adim:{},
                    Marial_Bai:{}
                  

                },
                Ayat_Centre:{
                    Ajok:{},
                    Wun_Giir:{}
                },
                Aweil_Town:{
                    Ayuang:{},
                    Hai_Salam:{},
                    Haya_Toich:{},
                    Machar_Kunyuk_Block_A:{},
                    Machar_Kunyuk_Block_B:{},
                    Madiria:{},
                    Malou_Aweer:{},
                    Mathiang:{},
                    Naivasha:{},
                    Zirah:{}
                },
                Achana:{
                    Achana:{},
                    Mangok_Dengdit:{}
                }
                

            },
            Aweil_South:{
                Wathmuok:{
                    Achuan:{},
                    Majak_gooi:{},
                    Makuac_Amiir:{},
                    Pan_Ngapdit:{}
                },
                Tiar_aleit:{
                    Mangar_Lual:{},
                    Tiar_aliet:{}
                },
                Tar_weng:{
                    Majok_Abyei:{},
                    Makuei_Ngok:{},
                    Mayom_Achuil:{}
                },
                Panthou:{
                    Mading_Chan:{},
                    Riang_Aker:{}

                },
                Nyocawany_II:{
                    Alok:{}
                },
                Nyocawany_I:{
                    Hong_wekdit:{},
                    Mayom_Lach:{}
                },
                Nyieth:{
                    Pankuac:{},
                    Riang_Man_Kuek:{}
                },
                Gakrol:{
                    Akach:{},
                    Jerajiep:{},
                    Rum_aluel:{}
                },
                Ayai:{
                    Ajiith_Bok:{},
                    Amat_Weer:{},
                    Lach:{},
                    Majak_Cuei:{}
                }


            },
            Aweil_North:{
                Malual_West:{
                    Mabior_Nyang:{},
                    Majak_Baai:{},
                    Makuei:{},
                    Manyiel_Akok:{}
                },
                Malual_North:{
                    Gok_Machar:{},
                    Gor_Ayen:{},
                    Malual_Loc:{},
                    Mayom_Adhal:{},
                    Peth_Atak:{}
                },
                Malual_East:{
                    Abyei_Chok_I:{},
                    Abyei_Chok_II:{},
                    Jaach:{},
                    Mabior_Anguei:{},
                    Mayen_Ulem:{},
                    War_Geng:{},
                    War_Pach:{},
                    Wath_Thok:{}

                },
                Malual_Centre:{
                    Mareng_Akok:{},
                    Marol_Deng_Geng:{},
                    Pamat:{}
                },
                Ariath:{
                    Kajik:{},
                    Lueth_Ngor:{},
                    Majok_Ngor:{},
                    Ngop_Akot:{}

                }

            },
            Aweil_East:{
                Yargot:{
                    Garam:{},
                    Hal_bul:{},
                    Majok_Buol:{},
                    Makuac_Akuel:{},
                    Makuei_Wettong:{},
                    Marial_akeny_jok:{},
                    Nyak_ral:{}
                },
                Wunlang:{
                    Adool:{},
                    Gaal:{},
                    Majak_Gier:{},
                    Makuei_Agep:{},
                    Malual_Kuel:{},
                    Manyiel:{},
                    Rum_Athoi:{},
                    Rum_Manyiel:{},
                    Tong_Goi:{},
                    War_Dong:{},
                    Wunlang_Centre:{}
                },
                Mangok:{
                    Maboir_wundiing:{},
                    Maker_anei:{},
                    Makuach:{},
                    Mameer:{},
                    Mangok:{},
                    Marial_tong_liai:{},
                    Marol_duluit:{},
                    Riang_mal:{}

                },
                Mangar_tong_II:{
                    Ariak_Ariak:{},
                    Lol_akuei:{},
                    Mabil:{},
                    Machar_geng:{},
                    Malek_yel:{},
                    Panameth:{},
                    Tit_chok_mareeng:{}
                },
                Mangar_tong_I:{
                    Kan_ajak:{},
                    Mangar_tong:{},
                    Morol_Ajuong:{},
                    Rialdit_I:{},
                    Rialdit_II:{}
                },
                Malual_bai:{
                    Adoor:{},
                    Ajieriak:{},
                    Lieth:{},
                    Marial_ngab:{},
                    Marol_lach:{},
                    Mathiang_Nientok:{},
                    Peth:{},
                    Wun_kuel:{}
                },
                Madhol:{
                    Ajiep:{},
                    Amarjal:{},
                    Amoth_Akok:{},
                    Dokul:{},
                    Mabok_Tong:{},
                    Majok_Dut:{},
                    Majok_Yinthiou:{},
                    Makuac_Kiir:{},
                    Malualdit:{},
                    Marol_Akot:{},
                    Pagai:{},
                    Rumrol:{},
                    Thonnyon:{},
                    War_baai:{}
                },
                Baach:{
                    Angoot:{},
                    Cuom_Ator:{},
                    Malou:{},
                    Malualkon:{},
                    Manyiel:{},
                    Mayenadhot:{},
                    Pariak:{},
                    Rulnyin:{},
                    Rum_Aker:{},
                    Uyon:{},
                    Waragany:{},
                    Warawar:{}
                }

            },
            Aweil_Centre:{
                Nyalath:{
                    Majok_Rok:{},
                    Udhaba:{}
                },
                Chel_South:{
                    Cham_Anguei:{},
                    Luang_Aher:{},
                    Makuac_Amudho:{}

                },
                Bar_Mayen:{
                    Alok:{},
                    Baau:{},
                    Kabat:{},
                    Moundit:{},
                    Panjap:{},
                    Pinywella:{},
                    War_Aher:{}

                },
                Awiil:{
                    Amothic:{},
                    Aweil_Tiik:{},
                    Kum_Kat:{},
                    Panameth:{},
                    Rol_Abola:{},
                    Rum_Anguoth:{},
                    War_Rak:{}
                },
                Aroyo:{
                    Aroyo:{},
                    Kur_chok:{}
                },
                Achana:{
                    Lulich:{},
                    Umar:{}
                },
                Abul:{
                    Abul:{},
                    Awada:{},
                    Hai_Mathar:{},
                    Muni:{}
                }

            }

        },
        Lakes:{
            Yirol_West:{
                Abang:{
                    Benylom:{},
                    Pakeu:{},
                    Pankar:{},
                    Wathcabath:{}
                },
                Aluakluak:{
                    Agany:{},
                    Aluakluak :{} 
                },
                Anuol:{
                    Ateerbaai:{},
                    Kathiar:{}
                },
                Genggeng:{
                    Akekoi:{},
                    Kunyir:{},
                    Pabur:{}
                },
                Gher:{
                    Gher:{},
                    Yibor:{}
                },
                Mapuordit:{
                    Agutraan:{},
                    Mabui:{}
                },
                Yirol :{
                    Amatnhom:{}
                } 
            },
            Yirol_East:{
                Adior:{
                    Ayiem:{},
                    Macharaciek:{},
                    Mamer:{},
                    Shambe:{}
                },
                Lekakedu:{
                    Akeu:{},
                    Aruomnyiel:{},
                    Bunagany:{},
                    Nyang:{}
                },
                Malek:{
                    Langmatot:{},
                    Malek:{},
                    Thian:{}
                },
                Pagarau:{
                    Machuor:{},
                    Pagarau:{}
                },
                Tinagau:{
                    Achigor:{},
                    Tinagau:{}
                },
                Yali:{
                    Akuai:{},
                    Kap:{},
                    Wunthou:{}
                }
            },
            Wulu:{
                Bargel:{
                    Bargel:{},
                    Gulmar:{},
                    Makor:{}
                },
                Domoloto:{
                    Deteku:{},
                    Dokuru:{},
                    Wakou :{}
                },
                Makundi:{
                    Bidibadai:{},
                    Kombi:{},
                    Makundi:{}
                },
                Wulu  :{
                    Tonjo:{},
                    WuluGedim:{}
                }
            },
            Rumbek_North:{
                Aloor:{
                    Catom
                },
                Madol:{
                    Biar:{},
                    Panhiamacot :{}
                },
                Malueeth:{
                    Acieek:{},
                    Kak:{},
                    Madhol   :{}

                },
                Maper:{
                    MaperCentre 
                },
                Mayen:{
                    Amok:{},
                    Mayen:{},
                    Wundhiot:{}
                },
                Wunrieng:{
                    Chamcuer:{},
                    Wunrieng:{}
                }
            },
            Rumbek_East:{
                Aduel:{
                    Aduel:{},
                    Billing:{},
                    Thonic :{}
                },
                Akot:{
                    Amethagok:{},
                    Atiriu:{}
                },
                Atiaba:{
                    Atiaba:{},
                    Karic :{}
                },
                Cueicok:{
                    Makembele:{},
                    Warnyinyam:{}
                },
                Malengagok:{
                    Kuelkuac:{},
                    Majak:{}
                },
                Pacong:{
                    Pacong:{},
                    Panawac:{}
                },
                Paloch:{
                    Golkou:{},
                    Pagang:{}
                }
            },
            Rumbek_Centre:{
                Amongpiny:{
                    Adol:{},
                    Amongpiny:{}
                },
                Jiir:{
                    Abarkou:{},
                    Abinajok:{},
                    Akoljal:{}
                },
                Malek:{
                    Apeet:{}
                },
               
                Matangai:{
                    Abeer:{},
                    Cholocok:{},
                    Nyangkoot :{}
                },
                Mayom:{
                    Cueicok:{}
                }
            },
            Cueibet:{
                Abiriu:{
                    Amethduol:{},
                    BilingGuet:{},
                    MarialAkeeng:{},
                    Mayath :{}
                },
                Citcok:{
                    Akot:{},
                    Mabil:{},
                    MajokRual:{},
                    Ramateer:{},
                    Tiaptiap:{}
                },
                Duony:{
                    Agok:{},
                    Malou:{}
                },
                MalouPec:{
                    AcolMalek:{},
                    LudoCok:{},
                    Makuei:{},
                    Malou:{}
                },
                Ngap:{
                    Ciminti:{},
                    KiloSeven:{},
                    Malou:{}
                },
                Pagor :{
                    Anaak:{},
                    Yardong :{}
                }
            },
            Awerial:{
                Abuyong:{
                    Abuotbaai:{},
                    Gutthom:{},
                    Maboradhiak:{},
                    Makur:{}
                },
                AlelI:{
                    Jarweng :{} 
                },
                AlelII:{
                    Thanytoc:{}
                },
                Bunagok :{
                    Aguarkuoth:{},
                    Hor :{}
                },
                Dor:{
                    Ariaga:{},
                    AtorokI:{},
                    AtorokII:{},
                    Maborjila:{},
                    Patiemthou:{},
                    Wutrek:{}   
                },
                Magok:{
                    Joot:{},
                    Matjuor :{}
                },
                Nile:{
                    Limkethi:{},
                    Wunthou:{}
                },
                Puluk:{
                    Duonygok:{},
                    Kalthok:{},
                    Mingkaman:{}
                }
            }

        },
        Western_Equatoria:{
            Tambura:{},
            Nagero:{},
            Nzara:{},
            Ibba:{},
            Mvolo:{},
            Ezo:{},
            Yambio:{},
            Mundri_East:{},
            Mundri_West:{},
            Maridi:{}
        },
        Central_Equatoria:{
            Yei:{
                Lasu:{
                    Asoli:{},
                    LasuCentre :{}  
                },
                Mugwo:{
                    Jombu:{},
                    Longamere:{},
                    Payawa:{},
                    Yari :{}
                },
                Otogo:{
                    Goja:{},
                    Logo:{},
                    Mongo:{},
                    Ombasi:{},
                    Wotogo:{}
                },
                Tore:{
                    Adio:{},
                    Avokaya:{},
                    Baka:{},
                    Mundu:{}
                },
                YeiTown   :{
                    Gimunu:{},
                    Hai_SobeZone:{},
                    Jigomoni:{},
                    JonsukZone:{},
                    LutayaZone:{},
                    Minyori:{},
                    Pakula:{},
                    Ronyi:{},
                    SanjasiriZone:{},
                    YaridaniZone:{}
                }
            },
            Terekeka:{
                Gameiza:{
                    Gameiza:{},
                    Geri:{},
                    Kanyawayi:{},
                    Korsoba:{}
                },
                MangalaNorth:{
                    Logori:{},
                    MangalaCentre:{},
                    Wanyang:{}
                },
                Muni:{
                    Bokana:{},
                    Gabuta:{},
                    Gori:{},
                    Tukoro:{},
                    Yukara:{}
                },
                Nyori:{
                    Loki:{},
                    Maridi:{},
                    Mayoung:{},
                    Nyori :{}  
                },
                Reggo:{
                    BujuLojora:{},
                    Buranga:{},
                    Longi:{},
                    Mirindia:{},
                    Mogiri:{}
                },
                Rijong:{
                    JonkokPayaya:{},
                    Kowori:{},
                    Langi:{},
                    Mula:{},
                    RijongCentre :{} 
                },
                Tali:{
                    Bari:{},
                    Dari:{},
                    Dudu:{},
                    Jaming:{},
                    Jobur:{},
                    Jokari:{},
                    Makido:{},
                    Mijiki:{},
                    Pagara:{}
                },
                Terekeka:{
                    Buko:{},
                    Jor:{},
                    JubaGondi:{},
                    Nyikabur :{}
                },
                Tindilo:{
                    Bureng:{},
                    Gworonga:{},
                    MundariBura:{},
                    Rume:{},
                    Somaring:{}
                },
                Tombek:{
                    Bori:{},
                    BoriAringa:{},
                    Naguli:{},
                    Swaklee:{}
                }
            },
            Morobo:{
                Gulumbi:{
                    Girili:{},
                    Kendila:{},
                    Kilikili:{},
                    Kindi:{}
                },
                Kimba:{
                    Kaya:{},
                    KimbaCentre:{},
                    Yondu:{}
                },
                Lujulo:{
                    Kembe:{},
                    Kendre:{},
                    Yugufe :{}
                },
                Panyume:{
                    Morjame:{},
                    PanyumeCentre:{},
                    Yaribe  :{}
                },
                Wudabi:{
                    Aloto:{},
                    Geri:{},
                    Nyei:{}
                }
            },
            Lainya:{
                Kenyi:{
                    KenyiCentre:{},
                    Limbe:{},
                    LokaWest :{}
                },
                Kupera:{
                    Korobe:{},
                    Kupera:{},
                    Mundu:{}
                },
                Lainya:{
                    Bereka:{},
                    Logwili:{},
                    Lokurubang:{}
                },
                Mukaya:{
                    Biri:{},
                    DimuOne:{},
                    Lorega:{}
                },
                Wuji  :{
                    Dongoro:{},
                    Koyoki:{},
                    WujiCentre:{}
                 }
            },
            Kajo_Keji:{
                KangapoI:{
                    Kigwo:{},
                    Kiri:{},
                    Leikor:{},
                    Limi:{},
                    Litoba:{},
                    Moijo:{},
                    Pomoju:{},
                    SeraJale:{}
                },
                KangapoII:{
                    Bori:{},
                    Jalimo:{},
                    Kinyiba:{},
                    Logili:{},
                    Logu:{},
                    Wudu:{}
                },
                Lire:{
                    Kudaji:{},
                    Likamerok:{},
                    Longira:{},
                    Mekir:{},
                    Mere:{},
                    Romogi:{}
                },
                Liwolo:{
                    Ajio:{},
                    Kala:{},
                    Kendiri:{},
                    Kerwa:{},
                    Mangalatore:{},
                    Sokare :{}
                },
                Nyepo :{
                    Gederu:{},
                    Kansuk:{},
                    Lori:{},
                    Rodo:{}
                }   
            },
            Juba:{
                Bungu:{
                    Bele:{},
                    KworojikBungu:{},
                    YenoKeji :{}
                },
                Dolo:{
                    KuAda:{},
                    Sirimon:{},
                    Sure:{},
                    Tulyang:{}
                },
                Ganji:{
                    Ganji:{},
                    Kagwada:{},
                    Kulipapa:{}
                },
                Gondokoro:{
                    Garbu:{},
                    Kango:{},
                    Monanyik :{} 
                },
                JubaTown:{
                    DressesLine:{},
                    HaiBuluk:{},
                    HaiCinema:{},
                    HaiCommercial:{},
                    HaiGabat:{},
                    HaiMalakal:{},
                    HaiMayo:{},
                    HaiNeem:{},
                    HaiNeggily:{},
                    HaiNyakama:{},
                    HaiOrselim:{},
                    HaiSoura:{},
                    HaiZendia:{},
                    JubaNabari:{},
                    JubaQuarterCouncil:{},
                    MTC:{},
                    NimraTalata:{},
                    Tomping:{}
                },
                Kator:{
                    Atlabara:{},
                    KatorCentre:{},
                    KonyoKonyo:{},
                    Lologo:{}
                },
                Lirya:{
                    Langabu:{},
                    LiryaCentre:{},
                    Lyongori:{},
                    Ngangala:{},
                    Ngulere :{}
                },
                Lobonok:{
                    Karpeto:{},
                    Kelang:{},
                    Kitone:{},
                    Luwalla:{},
                    Tombur:{}
                },
                Lokiliri:{
                    Aru:{},
                    JalietKudow:{},
                    LokiliriCentre:{},
                    Odemu:{}
                },
                MangalaSouth:{
                    Bilinyang:{},
                    Magiri:{},
                    Mangkaro:{}
                },
                Munuki:{
                    DarSalam:{},
                    DarSalamJebel:{},
                    HaiKwuit:{},
                    HaiMouna:{},
                    HaiSeminary:{},
                    MunukiBlock_A:{},
                    MunukiBlock_B:{},
                    MunukiBlock_C:{},
                    MunukiIsland:{},
                    NyokuroEast:{},
                    NyokuronNorth:{},
                    NyokuronSouth:{},
                    NyokuronWest:{}
                },
                NorthernBari:{
                    JebelLadu:{},
                    JubaNaBari:{},
                    Luri:{},
                    Tendere:{}
                },
                Rejaf:{
                    Gumbo:{},
                    Kansuk:{},
                    LogoEast:{},
                    LogoEast:{},
                    Tokiman:{}
                },
                Rokon:{
                    Kugi:{},
                    Mirikiyo:{},
                    RokonCentre:{},
                    TokoKoTulu:{}
                },
                Tijor:{
                    Buko:{},
                    GuruLoToggu:{},
                    Ligi:{},
                    Nyarjwa:{},
                    TijorCentre:{},
                    Yorja:{}
                },
                Wonduruba:{
                    Katigiri:{},
                    Logwilu:{},
                    Loliwa:{},
                    Maliyo:{},
                    Moje:{},
                    Tuli:{}
                }
            },

        },
        Eastern_Equatoria:{
            Torit:{
                Bur:{
                    Autak:{},
                    Bolore:{},
                    Loronyo:{},
                    Loudo :{}
                },
                Himodonge:{
                    Hileu:{},
                    Imilai:{},
                    Keberek:{},
                    Otose:{}
                },
                Hiyala:{
                    Imatari:{},
                    MuraHatika:{},
                    Nyibira:{},
                    Tirrangore:{},
                    Tuhubak  :{}
                },
                Ifwotu:{
                    Hafai:{},
                    Ifwotu:{},
                    Imokoru:{},
                    Motti:{}
                },
                Imurok:{
                    Central_Imurok:{},
                    Chuful:{},
                    Ifoho:{},
                    Isalore:{}
                },
                Kudo:{
                    Hutala:{},
                    Lofiriha:{},
                    Loulang:{},
                    LowoiNorth:{},
                    LowoiSouth:{}
                },
                Torit:{
                    FodoFodo:{},
                    HaiWaiMesser:{},
                    Ibalany:{},
                    Ilangi:{},
                    Nyong:{}
                }
            },
            Magwi:{
                Lobone:{
                    Isore:{},
                    Lobone_I:{},
                    Lobone_II:{},
                    Lobone_III:{}
                },
                Magwi:{
                    Agoro:{},
                    Lofirha:{},
                    Magwi:{},
                    Obbo:{},
                    Palotaka:{},
                    Panyikwara :{}
                },
                Mugali:{
                    Longu:{},
                    Masindi:{},
                    Mugali:{}
                },
                Nimule:{
                    Abila:{},
                    Anzara:{},
                    Jelei:{},
                    Nimule:{}
                },
                Pageri:{
                    Kerepi:{},
                    Loa:{},
                    Moli:{},
                    Opari:{},
                    Pageri:{}
                },
                Pajok:{
                    OwinyKibul:{},
                    Pajok:{},
                    Pogee :{}
                }
            },
            Lafon_Lopa:{
                Arihilo:{
                    Dorik:{},
                    Tentet:{}
                },
                Burgilo:{
                    Lafon:{},
                    Nyadida:{},
                    Taar:{},
                    Wipuboi:{}
                },
                Imehejek:{
                    Ihirang:{},
                    MuraLopit:{}
                },
                Kurumi:{
                    Adeba:{},
                    Kuji:{},
                    Ugwil:{}
                },
                Lohutok:{
                    Iboni:{},
                    Lohutok:{},
                    Loming:{},
                    MuraLolongo:{}
                },
                Longiro:{
                    Idali:{},
                    Longiro:{},
                    Ngaboli:{}
                },
                Marguna:{
                    Amiru:{},
                    Bwodo:{},
                    Pubuli:{},
                    Ukwanya:{}
                },
                Pachidi  :{
                    Lwalla:{},
                    Payira:{},
                    Upuo:{}   
                }
            },
            Kapoeta_South:{
                KapoetaTown:{
                    Atalabara:{},
                    HaiTarawa:{},
                    Malakia:{},
                    Nalingaro:{},
                    Naminit:{},
                    Rei:{}
                },
                Longeleya:{
                    Goloki:{},
                    Kangatuny:{},
                    Lokwamor:{},
                    Lolemu:{},
                    Narekadai:{}
                },
                Machi_I:{
                    Korea:{},
                    Loming:{},
                    Lourien:{},
                    Napetet:{}
                },
                Machi_II:{
                    Lokwasinyon:{},
                    Nakware:{},
                    Namojongoronyit:{},
                    Natipiir:{},
                    Nayonaahaton:{}
                },
                Pwata:{
                    Lopala:{},
                    Moruarengen:{},
                    Nakicho:{},
                    Napetait:{},
                    Napong:{},
                    Nasiakina:{}
                }

            },
            Kapoeta_North:{
                Chumakori:{
                    Logerain:{},
                    Lotakawa:{},
                    Lowoyapuru:{},
                    Morunyang:{},
                    Napetet:{}
                },
                Karukomuge:{
                    Kamaliato:{},
                    Kibak:{},
                    Lokodei:{},
                    Lokoges:{},
                    Lopetet:{},
                    Morupus:{},
                    NabelenyTobok:{},
                    Nakwaa:{},
                    Nawao:{},
                    Nawebei:{},
                    Wakobu   :{}
                },
                Lomeyen:{
                    Loriwo:{},
                    Nalemusokon:{},
                    Naminitiot:{},
                    Napusiriet:{},
                    Natiir:{},
                    Rukruk :{}
                },
                Mosingo:{
                    Lokwamor:{},
                    Loregai:{},
                    Namonichek:{}
                },
                Najie:{
                    Lolepan:{},
                    Nadomeit:{},
                    Nangoletirie:{}
                },
                Paringa:{
                    Choroi:{},
                    Lowabok:{},
                    Nabekerminit:{},
                    Nacholobo:{},
                    Napustirai:{},
                    Nateregat:{},
                    Nawapetet:{},
                    Ngangorom:{},
                    Nyuda:{}
                }

            },
            Kapoeta_East:{
                Jie:{
                    Chumameri:{},
                    Napusiriet:{}
                },
                Katodori:{
                    Buno:{},
                    Kaibu:{},
                    Kair:{},
                    Kalokupe:{},
                    Kangikawo:{},
                    Katodori:{},
                    Koteen:{},
                    Lochwa:{},
                    Logir:{},
                    Lokuma:{},
                    Loregai:{},
                    Nakabangole:{},
                    Nakoromai:{},
                    Nalemumor:{},
                    Nalukupeta:{},
                    Namojee:{},
                    Nangatuny:{},
                    Nanglet:{},
                    NangorMoru:{},
                    Nanyapuduro:{},
                    Narii:{},
                    Narukeny:{},
                    Nawoit :{}
                },
                Kauto:{
                    Kuron:{},
                    NabwalEtoom:{},
                    Nachodokopelee:{},
                    Nakadengo:{},
                    Namolokonyit:{},
                    Namorpus:{},
                    Nanyangacor:{},
                    Napwotasigiria:{},
                    Nawoyapeta:{},
                    Peikim:{}
                },
                Lotimor:{
                    Lorengelop:{},
                    Naita:{},
                    Nakudochua:{},
                    Natubot:{}
                },
                Mogos:{
                    Katoogun:{},
                    Lochwa:{},
                    Lokitela:{},
                    Lotiyen:{},
                    Moruarengan:{},
                    Nadapalait:{},
                    Nasuwat:{}
                },
                Narus:{
                    Kalacha:{},
                    Kaldo:{},
                    Kalok:{},
                    Kamee:{},
                    Kanachidik:{},
                    Kapooe:{},
                    Lokubuo:{},
                    Lolim:{},
                    Lomuta:{},
                    Morunyang:{},
                    Naliel:{},
                    Narus:{}
                },
                Natinga :{
                    Kabehenyang:{},
                    Kamuto:{}
                }
            },
            Ikotos:{
                Hatire:{
                    Gilo:{},
                    Hatire:{},
                    Imilai:{},
                    Isore :{}
                },
                Ikotos:{
                    Huma:{},
                    Ikotos:{},
                    Ngutube:{},
                    Tseretenya:{}
                },
                Imotong:{
                    Geria:{},
                    Hiniso:{},
                    Ifosi:{},
                    Ingoi:{},
                    Lomuceny:{}
                },
                LomohidangNorth:{
                    Chahari:{},
                    Ibunyak:{},
                    Isoke:{},
                    Lobira:{},
                    Mangala:{}
                },
                LomohidangSouth:{
                    Chorokol:{},
                    Lobulo:{},
                    Lodwara:{},
                    Mak:{},
                    Okorohore:{},
                    Ramula:{}
                },
                Losite:{
                    Lotome:{},
                    Madial:{},
                    Nakoringole:{},
                    Namarati:{},
                    Napeyasi:{},
                    Lopus:{}
                }
            },
            Budi:{
                Kimotong:{
                    Kali:{},
                    Suguro:{},
                    Tataman:{}
                },
                Komori:{
                    Betalado:{},
                    Kikilai:{},
                    Komori:{},
                    Lohipor:{},
                    Lothigira:{},
                    Monita:{}
                },
                Loriyok:{
                    Kirongu:{},
                    Ngarich:{}
                },
                Lotukei:{
                    Itingi:{},
                    Lorema:{},
                    NewCush:{},
                    Piobokoi:{}
                },
                Loudo:{
                    Charit:{},
                    Kerewan:{},
                    Ngatuba:{}
                },
                Nagishot:{
                    Kadumakuc:{},
                    Nagishot:{},
                    Thuguro:{}
                },
                Napak:{
                    Chawa:{},
                    Kerenga:{},
                    Kudele:{},
                    Ngarahach:{}
                },
                Nauro:{
                    Kibongorok:{},
                    Kilanya:{},
                    Tala:{},
                    Tulugi  :{}
                }
            }
        }
    
  };
      
window.onload = function() {
  const stateSelection = document.querySelector("#state");
  const countySelection = document.querySelector("#county");
  const payamSelection = document.querySelector("#payam");
  const bomaSelection = document.querySelector("#boma");

  // Disable county, payam and boma selection until state is selected
  countySelection.disabled = true;
  payamSelection.disabled = true;
  bomaSelection.disabled = true;

  // Clear all options from county, payam and boma selection
  countySelection.length = 1;
  payamSelection.length = 1;
 

  // Populate state selection with options from statesinfo
  for (let state in statesinfo) {
    stateSelection.options[stateSelection.options.length] = new Option(
      state,
      state
    );
  }

  // Update county selection when state is changed
  stateSelection.onchange = (e) => {
    countySelection.disabled = false;
    payamSelection.disabled = true;
    bomaSelection.disabled = true;

    // Clear all options from payam and boma selection
    payamSelection.length = 1;
    bomaSelection.length = 1;

    // Clear all options from county selection except first one
    countySelection.options.length = 1;

    // Populate county selection with options from selected state
    for (let county in statesinfo[e.target.value]) {
      countySelection.options[countySelection.options.length] = new Option(
        county,
        county
      );
    }
  };

  // Update payam selection when county is changed
  countySelection.onchange = (e) => {
    payamSelection.disabled = false;
    

    // Clear all options from payam selection except first one
    payamSelection.options.length = 1;

    // Populate payam selection with options from selected county
    for (let payam in statesinfo[stateSelection.value][e.target.value]) {
      payamSelection.options[payamSelection.options.length] = new Option(
        payam,
        payam
      );
    }
  };
//  countySelection.onchange = (e) => {
// payamSelection.disabled = false;
 bomaSelection.disabled = true;

payamSelection.onchange = (e) => {
  bomaSelection.disabled = false;
  // Clear all options from boma selection except first one
  bomaSelection.options.length = 1;

  // Populate boma selection with options from selected payam
  for (let boma in statesinfo[stateSelection.value][countySelection.value][payemSelection.value][e.target.value]) {
    bomaSelection.options[bomaSelection.options.length] = new Option(
      boma,
      boma
    );
  }
};
};

  